/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface TestComponentYoobic {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestComponentYoobicElement extends Components.TestComponentYoobic, HTMLStencilElement {
    }
    var HTMLTestComponentYoobicElement: {
        prototype: HTMLTestComponentYoobicElement;
        new (): HTMLTestComponentYoobicElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "test-component-yoobic": HTMLTestComponentYoobicElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface TestComponentYoobic {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "test-component-yoobic": TestComponentYoobic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-component-yoobic": LocalJSX.TestComponentYoobic & JSXBase.HTMLAttributes<HTMLTestComponentYoobicElement>;
        }
    }
}
